### ISSUE TITLE
[General] .dol file does not support ForwardMii

### ISSUE THREAD

**Issue by TrashBandatcoot** [Mefiresu/RSDKv5-Decompilation#15]
I created a forwarder using CustomizeMii's ForwardMii plugin, but upon booting I just get to see a black screen. Will this get fixed?

(Here's a screenshot in case if anyone is curious what the forwarder looks like.)
![image](https://user-images.githubusercontent.com/49070403/198300674-9c0241c1-db67-409a-8d6a-8fbc3f4d5a17.png)

**Comment by Mefiresu** [comment]
I don't know much about how this forwarder works, but my guess is that it doesn't change directory before starting the game. So maybe just having the game files at the root of the SD card should work.

**Comment by Mefiresu** [comment]
After testing it myself, it seems to work just fine when the Data.rsdk file is in the `/apps/SonicMania` folder.
Could you tell me how you created yours to understand what went wrong?

**Comment by TrashBandatcoot** [comment]
I used CustomizeMii combined with the ForwardMii plugin, the attached image should show you how straight foward that is. After launching, it does load the boot.dol file, but after that just stops on a black screen and never seems to load the Data.rsdk file. Just to be sure, I opened the game through the Homebrew Channel and it worked fine there. Maybe you used some other forwarder creator I could use instead?

![image](https://user-images.githubusercontent.com/49070403/198347888-677fef96-c20c-4a9c-a010-242e7432f563.png)

**Comment by Mefiresu** [comment]
Figured out why it worked for me, I actually had another Data.rsdk file at the root of the SD card.
My first theory was correct then, the forwarder doesn't change the current directory before starting the executable.

I will push a fix soon to hardcode the game path to a specific folder at the root of the SD card (like `RSDKv5`), so that future versions will read/write game files from there instead of next to the boot.dol.

**Comment by Mefiresu** [comment]
Fixed by [4ecdeb0](https://github.com/Mefiresu/RSDKv5-Decompilation/commit/4ecdeb0b8aa2e2150c742ac40d0161244b032e89).
