### ISSUE TITLE
[Wii] Sonic Mania Mods and DevMode

### ISSUE THREAD

**Issue by Repliroid** [Mefiresu/RSDKv5-Decompilation#24]
In the Wii Version, Is it possible to add Mods?

**Comment by Mefiresu** [comment]
The next release will support some simple mods, though not all, because of memory restrictions and the fact that the Wii lacks a way to dynamically load and run custom code.

As for the devMenu, you can already enable it by modifying the Settings.ini [Game] section to add:

```
devMenu=y
enableControllerDebugging=y
```

Then press - on your controller to open/close the dev menu.
