### ISSUE TITLE
Trying to Compile

### ISSUE THREAD

**Issue by godreborn** [Mefiresu/RSDKv5-Decompilation#9]
I'm trying to compile this, but I get this error: make: *** No rule to make target 'bin/obj/Wii/Game/Game/Game.o', needed by 'bin/Wii/GX/RSDKv5.elf'.  Stop

I don't know if I'm using the right devkitPPC version or not.  I'm on the latest for everything.

**Comment by Mefiresu** [comment]
You need to use this fork alongside the [Sonic Mania Decompilation](https://github.com/Rubberduckycooly/Sonic-Mania-Decompilation). The `Game` symlink needs to point to it in order to compile the game together with RSDKv5.
Since this is a WIP port, I haven't had the time to write a complete guide to build it.
If you have questions or need further assistance, please join the REMS discord: https://dc.railgun.works/retroengine
